apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: eiu65j7tg-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: eiu65j7tg-go 
  name: eiu65j7tg-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: eiu65j7tg-go 
