apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: eiu65j7tg-go 
  janus-idp.io/tekton: eiu65j7tg-go
  backstage.io/kubernetes-id: eiu65j7tg-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: eiu65j7tg-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml